
try
{
    string o = nil;
    o.size();
}
catch (exception e)
{
    print("caught: ");
    print(e);
    print("\n");
}
